### ISSUE TITLE
是我用錯了嗎？

### ISSUE THREAD

**Issue by orocannoneer** [Maooookai/po_and_excel_transfer_tool#1]
PS E:\po_and_excel_transfer_tool> python po_to_xlsx.py
po转xlsx工具 by mirage
输入po文件路径：E:\MEGA\renpy-ttk-1.8\out\BT-0.2.0c-pc-T_Chinese.po
Traceback (most recent call last):
  File "E:\po_and_excel_transfer_tool\po_to_xlsx.py", line 10, in <module>
    sht = wb.sheets["sheet1"]
  File "C:\Users\ff760\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\main.py", line 88, in __getitem__
    return self(key)
  File "C:\Users\ff760\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\main.py", line 5109, in __call__
    return Sheet(impl=self.impl(name_or_index))
  File "C:\Users\ff760\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\_xlwindows.py", line 940, in __call__
    return Sheet(xl=self.xl(name_or_index))
  File "C:\Users\ff760\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\_xlwindows.py", line 235, in __call__
    v = self._inner(*args, **kwargs)
  File "C:\Users\ff760\AppData\Local\Temp\gen_py\3.10\00020813-0000-0000-C000-000000000046x0x1x9.py", line 36625, in __call__
    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (9, 0), ((12, 1),),Index
pywintypes.com_error: (-2147352567, '發生例外狀況。', (0, None, None, None, 0, -2147352565), None)

**Comment by miraged3** [comment]
建议检查下文件权限问题，这个看上去是xlwings的报错。也可以回滚下xlwings版本到一年前左右试试，大概是xlwings==0.26.3到xlwings==0.27.7左右

**Comment by orocannoneer** [comment]
> 建议检查下文件权限问题，这个看上去是xlwings的报错。也可以回滚下xlwings版本到一年前左右试试，大概是xlwings==0.26.3到xlwings==0.27.7左右

回滾之後還是一樣的結果，後來我問GPT-4，請他幫我用其他方法實現了(遠目)
